// MIT License
// Copyright (c) 2026 Vít Procházka
//
// This is the main test of the Lock-Free Multi-Array Queue.
//
// The test creates a ring-buffer of 1024 Queues and puts <numberOfObjects> messages into one Queue
// and marks this Queue as "current" via an atomic variable.
//
// It then creates <numberOfThreads> "worker" threads that in each iteration do:
//
// 1. read the atomic variable (position of the "current" Queue in the ring-buffer)
// 2. try dequeue from the third/second/first Queue before the "current" Queue or the "current" Queue (random choice)
// 3. enqueue into the "current" Queue
//
// The test then constantly switches the atomic variable forward, effectively switching the "current" Queue
// to new and new Queues. Before each switch, it checks if the next "current" Queue is empty and if yes,
// it replaces it by a new Queue (this is to test the extension phases of the Queues as much as possible).
//
// At the end of the test (after all "worker" threads have terminated), the test goes over all Queues, dequeues
// all messages from them and checks if none is missing or duplicated (the order of the messages will of course be random).
//
// The enqueued/dequeued messages are uint64_t[1] (uint64_t arrays of size 1).
//
// 1) Build the assembly file into object files for Windows and Linux:
//
//    nasm -fwin64 -o LockFreeMultiArrayQueue.obj LockFreeMultiArrayQueue.asm
//    nasm -felf64 -o LockFreeMultiArrayQueue.o LockFreeMultiArrayQueue.asm
//
// 2) Under Windows (Microsoft Visual C++): In "x64 Native Tools Command Prompt for VS":
//
//    cl /W4 /EHsc LockFreeMultiArrayQueueMainTest.cpp LockFreeMultiArrayQueue.obj
//    .\LockFreeMultiArrayQueueMainTest.exe 20 4 200 5
//
// 3) Under Linux:
//
//    g++ -Wall -pthread -o LockFreeMultiArrayQueueMainTest LockFreeMultiArrayQueueMainTest.cpp LockFreeMultiArrayQueue.o
//    ./LockFreeMultiArrayQueueMainTest 20 4 200 5
//

#include <atomic>
#include <thread>
#include <vector>
#include <random>
#include <inttypes.h>

#include "LockFreeMultiArrayQueue.h"

#define CURRENT_MILLIS (std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count())
#define SLEEP_MILLIS std::this_thread::sleep_for(std::chrono::milliseconds(1))
#define SLEEP_SWITCH_MILLIS std::this_thread::sleep_for(std::chrono::milliseconds(switchMillis))

std::vector<LockFreeMultiArrayQueue<uint64_t>*> queueRingBuffer(1024);

std::atomic_uint64_t queueIndex;  // index of the "current" Queue in the ring-buffer

/*
 * The function run by the threads
 */
void mainTestTask(int threadNo, int64_t stopThreadsMillis)
{
    try
    {
        uint64_t ownIterations = 0;
        uint64_t ownDequeueEnqueuePairs = 0;

        std::random_device rd;   // a seed source for the random number engine
        std::mt19937 gen(rd());  // mersenne_twister_engine seeded with rd()
        std::uniform_int_distribution<> distrib(0, 3);  // distrib to transform the random unsigned int generated by gen into an int in [0, 3]

        uint64_t* message = NULL;

        for (; CURRENT_MILLIS < stopThreadsMillis ;)  // stop after stopThreadsMillis
        {
            // try dequeue from the third/second/first Queue before the "current" Queue or the "current" Queue (random choice)
            uint64_t qIndex = queueIndex;
            int randomOffset = distrib(gen);
            //printf("thread %d dequeueing at %" PRIu64 "\n", threadNo, (qIndex - randomOffset) & 0x3FFuL);
            message = queueRingBuffer[(qIndex - randomOffset) & 0x3FFuL] -> dequeue();

            // if successfully dequeued: enqueue into the "current" Queue
            if (NULL != message)
            {
                //printf("thread %d ENQUEUEING at %" PRIu64 "\n", threadNo, qIndex & 0x3FFuL);
                queueRingBuffer[qIndex & 0x3FFuL] -> enqueue(message, true);
                ownDequeueEnqueuePairs ++;
            }

            ownIterations ++;
        }

        printf("thread %d stopped after no of %" PRIu64 " iterations (%" PRIu64 " dequeue/enqueue pairs)\n",
               threadNo, ownIterations, ownDequeueEnqueuePairs);
    }
    catch (const std::exception &e)
    {
        printf("Exception caught: %s\n", e.what());
    }
}

/*
 * Main function
 */
int main(int argc, char *argv[])
{
    try
    {
        int secondsToRun = 0;
        int numberOfThreads = 0;
        uint64_t numberOfObjects = 0;
        int switchMillis = 0;

        // handle command-line args
        try
        {
            if (5 == argc)
            {
                secondsToRun = std::stoi(argv[1]);
                numberOfThreads = std::stoi(argv[2]);
                numberOfObjects = std::stoul(argv[3]);
                switchMillis = std::stoi(argv[4]);

                if (switchMillis < 1) throw std::invalid_argument("<switchMillis> is less than 1 ms");
            }
            else throw std::invalid_argument("argc != 5");
        }
        catch (const std::exception &e)
        {
            printf("Exception caught: %s\n", e.what());
            printf("usage: usage: MainTest <secondsToRun> <numberOfThreads> <numberOfObjects> <switchMillis>\n");
            throw;
        }

        // set times of the phases of the test
        int64_t initMillis = CURRENT_MILLIS;
        int64_t stopThreadsMillis  = initMillis + (secondsToRun * 1000);  // the time at which all "worker" threads should stop
        int64_t postStopMillis     = stopThreadsMillis + 1000;  // start checking after all "worker" threads have stopped for sure

        printf("------- testing LockFreeMultiArrayQueue -------\n");

        // create the initial set of Queues
        queueRingBuffer[0] = new LockFreeMultiArrayQueue<uint64_t>("testQueue_0000", 1, -1);
        queueRingBuffer[1] = new LockFreeMultiArrayQueue<uint64_t>("testQueue_0001", 1, -1);
        queueRingBuffer[2] = new LockFreeMultiArrayQueue<uint64_t>("testQueue_0002", 1, -1);
        queueRingBuffer[3] = new LockFreeMultiArrayQueue<uint64_t>("testQueue_0003", 1, -1);
        queueIndex = 3;

        // allocate and enqueue the Objects
        printf("allocating and enqueueing into Queue %s:", (queueRingBuffer[queueIndex] -> getName()).c_str());
        for (uint64_t i = 0; i < numberOfObjects; i ++)
        {
            uint64_t* message = new uint64_t[1];
            message[0] = i;  // assign it a unique sequenceNumber
            printf(" [%" PRIu64 "]", message[0]);
            queueRingBuffer[queueIndex] -> enqueue(message, true);
        }
        printf("\n");

        // start the "worker" threads
        for (int i = 0; i < numberOfThreads; i ++)
        {
            std::thread t(mainTestTask, i, stopThreadsMillis);
            t.detach();
        }
        printf("%d threads started, millis: %" PRId64 "\n", numberOfThreads, (CURRENT_MILLIS - initMillis));

        // continuously switch the "current" Queue to new Queues
        //
        // we strongly assume that no "worker" thread is still active on 1 + queueIndex anymore,
        // because this would mean that such thread has been preempted for at least 1020 x 1 ms = cca 1 second
        // (1020 ms = (size of the ring-buffer minus 4) x smallest possible value of <switchMillis>)

        uint64_t queueCreates = 0;
        uint64_t queueReplaces = 0;
        uint64_t queueKeeps = 0;

        for (; CURRENT_MILLIS < stopThreadsMillis ;)
        {
            uint64_t qIndexNext = ((1 + queueIndex) & 0x3FFuL);
            uint64_t* message;

            if (NULL == queueRingBuffer[qIndexNext])
            {
                char qName[20];
                snprintf(qName, sizeof(qName), "testQueue_%04" PRIu64, qIndexNext);
                queueRingBuffer[qIndexNext] = new LockFreeMultiArrayQueue<uint64_t>(qName, 1, -1);
                queueCreates ++;
            }
            else if (NULL == (message = (queueRingBuffer[qIndexNext] -> dequeue())))
            {
                delete queueRingBuffer[qIndexNext];
                char qName[20];
                snprintf(qName, sizeof(qName), "testQueue_%04" PRIu64, qIndexNext);
                queueRingBuffer[qIndexNext] = new LockFreeMultiArrayQueue<uint64_t>(qName, 1, -1);
                queueReplaces ++;
            }
            else  // Queue is not empty: possible: the "worker" threads did not manage to empty it (in the previous pass over the ring-buffer)
            {
                printf("keeping Queue %s\n", (queueRingBuffer[qIndexNext] -> getName()).c_str());
                queueRingBuffer[qIndexNext] -> enqueue(message, true);
                queueKeeps ++;
            }
            queueIndex ++;  // actually switch queueIndex forward (this will be visible to the "worker" threads)
            //printf("queueIndex: %" PRIu64 "\n", queueIndex.load());
            SLEEP_SWITCH_MILLIS;
        }

        printf("stopped switching, millis: %" PRId64 "\n", (CURRENT_MILLIS - initMillis));

        // wait for all "worker" threads to have stopped for sure
        for (; CURRENT_MILLIS < postStopMillis ;) {
            SLEEP_MILLIS;
        }

        // check
        //
        // due to the non-deterministic scheduling and preempting of the threads,
        // the messages in the Queue will not be in any meaningful order,
        // but no message may be missing and no message may be duplicated!

        printf("start checking, millis: %" PRId64 "\n", (CURRENT_MILLIS - initMillis));

        std::vector<bool> checkArray(numberOfObjects);

        for (int i = 0; i < 1024; i ++)
        {
            if (NULL != queueRingBuffer[i])
            {
                uint64_t* message = queueRingBuffer[i] -> dequeue();
                if (NULL != message)
                {
                    printf("remained in %s: ", (queueRingBuffer[i] -> getName()).c_str());
                    do
                    {
                        if (checkArray[*message]) {
                            printf("******* Message [%" PRIu64 "] is duplicated *******\n", *message);
                            throw std::runtime_error("******* Message is duplicated *******");
                        } else {
                            checkArray[*message] = true;
                            printf(" [%" PRIu64 "]", *message);
                        }
                        delete message;
                    }
                    while (NULL != (message = queueRingBuffer[i] -> dequeue()));
                    printf("\n");
                }
                delete queueRingBuffer[i];
            }
        }

        for (uint64_t i = 0; i < numberOfObjects; i ++) {
            if (! checkArray[i]) {
              printf("******* Message [%" PRIu64 "] is missing *******\n", i);
              throw std::runtime_error("******* Message is missing *******");
            }
        }
        printf("queueCreates:   %15" PRIu64 "\n", queueCreates);
        printf("queueReplaces:  %15" PRIu64 "\n", queueReplaces);
        printf("queueKeeps:     %15" PRIu64 "\n", queueKeeps);
        printf("MainTest of LockFreeMultiArrayQueue finished successfully.\n");
    }
    catch (const std::exception &e)
    {
        printf("Exception caught: %s\n", e.what());
    }
}

